name: wethr
version: git
summary: Range functions app.
description: |

confinement: strict
base: core20

apps:
    wethr:
        command: bin/wethr

parts:
    wethr:
        plugin: npm
        npm-node-version: 14.16.1
        source: .
